### ISSUE TITLE
Export Unverified Payload

### ISSUE THREAD

**Issue by yosida95** [square/go-jose#135]
I want to access JWS payload before it gets verified.

**Use Case:**
I am building an Open ID Connect clients which accepts ID Tokens (i.e. JWTs signed by JWS) issued by multiple issuers.  In this client, parse a JWS payload at first, then recognize the issuer by `iss` claim of the payload and retrieve JWKs via Open ID Connect Discovery flow, finally verify the JWS using retrieved JWKs.

I looked for a go-jose's API that exports an unverified JWS payload but could not find.  Do you have any plans to support this use case?

**Comment by yosida95** [comment]
existing sample API provided by [jwk-go](https://github.com/dgrijalva/jwt-go): https://godoc.org/github.com/dgrijalva/jwt-go#Keyfunc

**Comment by csstaub** [comment]
That's not an unreasonable request, but exposing a generic API function to retrieve the payload without verifying it first is not something I want to include in the library. I'd be ok with adding a function for key retrieval in the jwt sub package, similar to what dgrijalva/jwt-go does; so that would allow doing this for JWT but not for generic JWS messages.

**Comment by ben-turner** [comment]
This could be quite useful for debugging if it was available in both packages. I don't see any way that it could be harmful to have it. Named appropriately, it would be unlikely that it could be confused for Verify. Alternatively, you could just export the field as something like `RawPayload`, which implies that it hasn't necessarily been verified yet.

**Comment by csstaub** [comment]
I disagree, I think it has a lot of potential for misuse. If you want to debug a JWS payload, you can always deconstruct it yourself by parsing the JSON and reading whatever you want out of it. JOSE already has enough sharp edges as it is, I'd rather not add another one.

**Comment by ben-turner** [comment]
I agree that it could be misused, but if it's clear that it's not intended to be used for in a certain way and a developer does it anyway, is that not the fault of the developer? The only reason that something like that should be avoided is if it will have side effects within the lib (eg. unexpected behaviour if the field is written to). It's not the job of a library to force the users to do things a certain way, its job is to provide the user with a clear, concise and consistent way to perform a task.

Take for example the stdlib `unsafe` package. The docs are very clear that it shouldn't normally be used, but it still exists. Why? Because if a developer is going to disregard the warnings and use it anyway, then they probably have a pretty good reason to and at that point, it's their job to make sure it doesn't break anything and not the go maintainers.

**Comment by csstaub** [comment]
This being a crypto library it's important for us to ensure that the interface is as safe as we can make it. There are other, better ways to solve the problem this issue is about that do not involve exposing the raw, unverified payload. As such I don't see the need for exposing the raw payload in this library. If you're parsing an unverified payload you're almost certainly doing something wrong and should reconsider what you're doing.

**Comment by losinggeneration** [comment]
I've run into needing this as well. It's pretty easy to do outside of the jose or jose/jwt library e.g [coreos/go-oidc](https://github.com/coreos/go-oidc/blob/master/verify.go#L81)

> There are other, better ways to solve the problem this issue is about that do not involve exposing the raw, unverified payload.
> If you're parsing an unverified payload you're almost certainly doing something wrong and should reconsider what you're doing.

Would you be willing to elaborate how you'd solve the problem of multiple issuers? The solution I came up with was passing the issuer along that could be used to get the JWK without inspecting the JWS payload. With this or parsing the the JWT without validation I wouldn't trust the issuer outright. I would still have to make sure it's a known issuer.

**Comment by csstaub** [comment]
If you have multiple issuing keys, you can set the key ID (`kid`) field in the JWS header and select the key used to verify a payload based on that value. The key ID field is exposed in the read-only header (https://godoc.org/gopkg.in/square/go-jose.v2#Header) which can be accessed after parsing a JWS message.

**Comment by losinggeneration** [comment]
That's for the response @csstaub That seems like it would work well but it requires knowing every issuer prior to being able to verify the JWS.

In my case, I'm using a single service that provides multiple issuers. So I have a known base URL `https://example.com` in this example. The `iss` field includes the issuing resource as part of the URL that can be pulled out `{issuer}` to construct a URL with the known base URL to get the JWKs. For example, `https://example.com/{issuer}/.well-known` is the OpenID Connect `well-known` configuration endpoint that provides the endpoint to get the JWKs for that issuer. Then the normal verification process can happen.

**Comment by csstaub** [comment]
That seems like an odd pattern -- how do you verify that the JWKs you fetch from your base URL are trusted? How do you know you can trust them? 

We could certainly introduce a callback that would allow you callers to fetch keys based on the issuer field in a token. I'm happy to have a callback for something specific such as this if it's required to implement a particular protocol, but I'd rather not expose the entire raw payload .

**Comment by losinggeneration** [comment]
> how do you verify that the JWKs you fetch from your base URL are trusted? How do you know you can trust them?
It makes the assumption that `https://example.com` is in your control & has a valid SSL cert for that domain. The base url is also something specifically set for that service.

**Comment by csstaub** [comment]
Alright. I'm happy to accept a PR that adds a callback for fetching keys on demand.
