### ISSUE TITLE
LoadPublicKey and LoadPrivateKey are in package main

### ISSUE THREAD

**Issue by solarfly73** [square/go-jose#140]
The utils LoadPublicKey and LoadPrivateKey functions are listed in godoc as part of the library, but these are in the main package of jose-util and can't be accessed. Is there a reason the utils.go isn't outside of main and accessible as library calls?

**Comment by csstaub** [comment]
Both of those functions were present in the jose package in `v1`, but were removed from `v2` (and moved into jose-util for internal use). IMO the functions were badly designed and shouldn't be used. They try to parse multiple different formats for compat but in a bit of a haphazard way. Rather than doing this, your app should know what it's parsing or use a third-party library that specifically focuses on getting this right.

**Comment by christianhuening** [comment]
@csstaub You should adjust the docs, as they still say that LoadPublicKey and LoadPrivateKey are included with v2 (see: https://godoc.org/gopkg.in/square/go-jose.v2, JWS example).

**Comment by csstaub** [comment]
@christianhuening You are indeed correct, thanks for pointing that out. I will update the examples to remove the references to those functions.

**Comment by nitecoder** [comment]
@csstaub , can you please suggest a library that would be a good replacement for these functions (if such exists)?

**Comment by csstaub** [comment]
There are functions for loading public/private keys in the Go standard library, e.g. in [crypto/x509](https://golang.org/pkg/crypto/x509). Is there a particular format of key that you're trying to parse that's not covered in there?
