### ISSUE TITLE
JWS FullSerialize panics with *JSONWebKey Signer & EmbedJWK.

### ISSUE THREAD

**Issue by cpu** [square/go-jose#157]
Hi folks :wave:

The [ACME protocol](https://tools.ietf.org/html/draft-ietf-acme-acme-07) built on top of JOSE/JWS allows for both requests that use JWS with embedded JWKs as well as JWS with the JWK identified by the Key ID in the signature but not embedded. In [Boulder](https://github.com/letsencrypt/boulder/)'s implementation of ACME [we choose to reject any requests that contain both types at once](https://github.com/letsencrypt/boulder/blob/b0e490ed3f065ef51f8a025baf4d8d6e42a3f497/wfe2/verify.go#L95:L99) as the protocol considers them mutually exclusive forms.

I was trying to create a test vector using go-jose v2 that would contain both a Key ID and an embedded JWK to exersize the rejection codepath when I noticed go-jose will panic if a `*jose.JSONWebKey` is used as the `SigningKey.Key` with `jose.SigningOptions{ EmbedJWK: true}` if the signer's produced JWS are serialized with `FullSerialize()`:
> panic: json: error calling MarshalJSON for type *jose.JSONWebKey: square/go-jose: unknown key type '%!s(<nil>)'

A [small reproduction program](https://gist.github.com/cpu/8b757575355c16495733e12ea6cf89cf) might explain the issue clearer.

My experience with JOSE/JWS is 100% ACME based in a setting in which there's no reason to construct a `SigningKey` using a `*jose.JSONWebKey` while also setting `EmbedJWK` (except to make whacky test vectors!) but I can't speak to other users and whether this is a true bug or just a corner case that should have been rejected earlier than serialization.

Is this a case of "If it hurts stop doing it" or should the library have handled this without a panic?

Thanks!

**Comment by csstaub** [comment]
I can't think of a use-case for this, but we should probably fix the panic anyway. The library shouldn't panic like that, if there's an issue it should return an error.

**Comment by csstaub** [comment]
Ah, I see what the problem is. The JWK contains a private key, and that private key is stripped when copying the key id when building the signer (we don't want to accidentally embed the private key, after all). However this causes EmbedJWK to panic because the key field is now `null`. I'm probably going to fix the panic but without making it possible to do this, there's no generic API to get the public key from the private key and we definitely don't want private keys to be embedded anywhere (that'd be a huge footgun).

**Comment by csstaub** [comment]
Ah, actually my analysis was slightly off. The problem was the the key was wrapped in a JWK, and it was doing some operations wrong and not preserving the public key constructed when creating a recipient object for the public key.

**Comment by csstaub** [comment]
Ugh, ok, this is yet another silly part of the JOSE spec. I'm going to change the implementation so that we either embed the JWK, or set the key ID, but never do both. That'll make it impossible to generate a JWS that has both the JWK with a kid and a protected header field with a kid. This unfortunately means you wont' be able to use go-jose to create silly test vectors.

**Comment by cpu** [comment]
@csstaub Thanks for the analysis! I agree that this is the right fix to make. I already have my goofy test vector and it's much better to protect the API against misuse than to enable that :-)

**Comment by csstaub** [comment]
Released fix in https://github.com/square/go-jose/releases/tag/v2.1.3

**Comment by cpu** [comment]
@csstaub Great, thank you! :trophy:
