### ISSUE TITLE
Signature verification chicken-and-egg problem

### ISSUE THREAD

**Issue by rapropos** [square/go-jose#17]
I have a situation where information included in an incoming payload is needed to know which key to use to verify the signature on a request, and cannot figure out how to achieve this with the current API. Would there be a downside to exposing the JsonWebSignature's payload field in some fashion that does not yet require knowing the key needed for verification? I am looking to do something like:
```
json.Unmarshal(jwo.Payload(), &req)
database.FindId(req.SubmitterId, &submitter)
jwo.Verify(submitter.SigningKey)
```
Thank you for your consideration.

**Comment by csstaub** [comment]
It would be preferable to store this information inside a header value, such as the `kid` (key id) header field. I'm currently working on exposing these header values in my `cs/jwk` branch. Selecting the verification key based on the payload seems like an anti-pattern to me, I'd rather not expose the payload in a way that would allow callers to skip verification. Is there any reason you are unable to use header values for key selection?

**Comment by rapropos** [comment]
I was not aware that these header fields could be co-opted to contain arbitrary business logic data. The description of the `kid` field in the draft spec seemed to suggest that it was intended for a situation where a single signer has multiple keys. In my application, a server needs to respond to many different signers, and the verification process consists of making sure that each successive request is signed with the key that was registered for that signer during an initial registration process.

I will try using a header field and your experimental branch.

**Comment by rapropos** [comment]
So far I have been unsuccessful attempting to set the KeyId field in such a fashion so that it arrives at the server. I marshal my payload object into a `[]byte`, pass that to `Sign()`, set `Signatures[0].Header.KeyId` on the resulting signed object, call `FullSerialize` and send the result over the wire. When it arrives on the server side, the `KeyId` field of the header is blank. A cursory inspection of the `JsonWebSignature` object before it is serialized shows both a `KeyId` field in the `Signatures` array (which contains the proper value I set) and a `KeyId` field inside the `rawHeader` structure (which is blank). I see that the comments around the definition of the `JoseHeader` type call it "read-only", which may be the crux of my problem. Is there a supported way to get that 'kid' header field set via the go-jose library in addition to reading it?

**Comment by csstaub** [comment]
As of right now, the experimental branch does not yet have support for setting header values, only reading them. I don't have a clear timeline for adding support for that yet, but patches are welcome. Either way though, setting the header values on the `JoseHeader` struct would not work since the header values would already have to be known at the time of signing to produce a proper message. The way the interface will likely work is that you could set header fields on a `Signer`, which would then get included with all messages produced by that signer.

Also, if you want to tie a key to an identity then you may want to explore the use of certificates instead. But that all depends on your design and threat model.
