### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by philtay** [square/go-jose#223]
what about this plan?
* v2 branch should be merged back to master
* add `go.mod` and `go.sum` files in the repository root (master)
* cut new release

**Comment by mbyczkowski** [comment]
I think it would be great to eventually move go-jose to use Go modules and just use master branch for development (as opposed to `v1` and `v2`). However we want to be careful, so people using old imports (like `gopkg.in/square/go-jose.v2`) still get the updates without making code changes.

This could be a good time to create a `v3` release and figure out support plan for `v1` and `v2`(would they still be actively maintained? receive security fixes only?).

Since we tag releases, go-jose as a lib already works pretty well for people using Go modules, so there's no rush here to migrate. I think Go modules would be more useful for tools that we include in this repo (like `jose-util`). Should those programs be separate modules though (or be moved to a different repo)? I don't know if we have an answer to that, yet.

**Comment by csstaub** [comment]
I agree with @mbyczkowski's assessment, since Go modules support gopkg.in import paths go-jose should already work for people using Go modules for their code. If we were to switch to Go modules for the repo we'd probably do it in a v3 release but I don't see a benefit to that, at the moment.

**Comment by shaxbee** [comment]
Go module support would enable caching go-jose in proxy (such as gocenter.io)
dramatically reducing build times which is crucial for CI.

**Comment by csstaub** [comment]
That's good to know, I wasn't aware of that. Maybe makes sense to plan a v3 then.
