### ISSUE TITLE
Policy on breaking changes

### ISSUE THREAD

**Issue by silasdavis** [square/go-jose#233]
I noticed a breakage on updating some of my dependencies that both depend on go-jose. It turned out was due to this change: https://github.com/square/go-jose/commit/985395ef3b634972a0a831dbc22a1ae9078c5607 

I would also have been reluctant to go to v3 for such a small change, but strictly this was a breaking change to the public (i.e. exported) API. If a v3 designation had been used they could have peacefully coexisted.

For future reference it would be useful to know whether this was a mistake or whether to expect some minor breaking changes like this within the same semantic major version? Perhaps this was an exception (it wouldn't break code that only made use of `NumericDate` locally for example). If there are likely to be more minor breaking changes in v2 would it be possible to flag them in a changelog?

Thanks for the library!

**Comment by csstaub** [comment]
Hi @silasdavis, you're right, that probably should have been flagged more explicitly. That was my mistake. We won't be publishing anymore breaking interface changes without bumping the major version. One thing I'm curious to ask, how do you feel about possibly breaking changes to bring the library in line with the JOSE standard? We've previously had bugs that caused incompatibilities that we fixed in a minor patch, with appropriate release notes. We could bump the major version for those kinds of changes as well in the future if that's something people would prefer.
