### ISSUE TITLE
is Expiry checked?

### ISSUE THREAD

**Issue by mhf-ir** [square/go-jose#327]
Seems be Expiry must be manual check instead of automatic checking.
Seems wrong implementation https://tools.ietf.org/html/rfc7519#section-4.1.4

```go
package main

import (
	"fmt"
	"time"

	"gopkg.in/square/go-jose.v2"
	"gopkg.in/square/go-jose.v2/jwt"
)

func main() {

	ttl := 2
	sharedKey := []byte("foobar")

	signer, err := jose.NewSigner(jose.SigningKey{Algorithm: jose.HS256, Key: sharedKey}, (&jose.SignerOptions{}).WithType("JWT"))
	if err != nil {
		panic(err)
	}

	Expiry := time.Now().UTC()
	Expiry = Expiry.UTC().Add(time.Second * time.Duration(ttl))

	claim := jwt.Claims{
		NotBefore: jwt.NewNumericDate(time.Now().UTC()),
		Expiry:    jwt.NewNumericDate(Expiry),
	}

	fmt.Println("Sign time is: ")
	fmt.Println(time.Now().UTC().Format(time.RFC1123))
	fmt.Println("Expiry time is: ")
	fmt.Println(Expiry.Format(time.RFC1123))
	token, err := jwt.Signed(signer).Claims(claim).CompactSerialize()
	if err != nil {
		panic(err)
	}

	parsed, err := jwt.ParseSigned(token)
	if err != nil {
		panic(err)
	}
	fmt.Println("First validation time is: ")
	fmt.Println(time.Now().UTC().Format(time.RFC1123))
	out := jwt.Claims{}
	if err := parsed.Claims(sharedKey, &out); err != nil {
		panic(err)
	}

	fmt.Println("Waiting for time to get Expiry limit")
	time.Sleep(4 * time.Second)
	fmt.Println("OK lets parse and check again")

	parsed2, err := jwt.ParseSigned(token)
	if err != nil {
		panic(err)
	}

	fmt.Println("Second invalid validation time is: ")
	fmt.Println(time.Now().UTC().Format(time.RFC1123))

	out2 := jwt.Claims{}
	if err := parsed2.Claims(sharedKey, &out2); err != nil {
		panic(err)
	}

	fmt.Println("Why valid?")
}
```

Output:
```
Sign time is: 
Mon, 24 Aug 2020 04:05:40 UTC
Expiry time is: 
Mon, 24 Aug 2020 04:05:42 UTC
First validation time is: 
Mon, 24 Aug 2020 04:05:40 UTC
Waiting for time to get Expiry limit
OK lets parse and check again
Second invalid validation time is: 
Mon, 24 Aug 2020 04:05:44 UTC
Why valid?
```

**Comment by gilbsgilbs** [comment]
Turns out `token.Claims()` only checks the signature of a JWT and not the registered claims. Once you have the claims, you must manually validate the registered claims like so:

```go
claims.Validate(jwt.Expected{
    Time: time.Now(),
})
```

I agree that this behavior is confusing to say the least. There should be a clear, complete and easily accessible example that shows how to safely check the validity of a JWT from start to end (i.e. verify both the signature and the validity of registered claims). The defaults could easily lead to bad implementations.

Currently, I can see at least two bad assumptions a developer using the jwt package could make:
- Expect `token.Claim(...)` to verify the registered claims by default (wrong: it just verifies the signature).
- Expect `claims.Validate(jwt.Expected{})` to use the current time by default (wrong: it ignores the `exp` and `nbf` claims if no `Time` field is specified in the `jwt.Expected` object).

@mbyczkowski Would you accept a PR that changes `claims.Validate` to use `time.Now()` instead of `time.Time{}` by default? While we could arguably say that this is a breaking change, I cannot see a valid use-case where one would expect to not validate the `exp` and `nbf` claims when they're set. Just looks like a better default to me. WDYT?

Otherwise, we could just add some complete examples in the docs (which would fix most of the issue I guess).
